__title__ = "contextional"
__description__ = "A functional testing tool for Python"
__url__ = "https://github.com/SalmonMode/contextional"
__version__ = "1.6.3"
__author__ = "Chris NeJame"
__author_email__ = "cnejame@truveris.com"
__license__ = "MIT"
