import sphinx_rtd_theme
# -*- coding: utf-8 -*-
#
# contextional documentation build configuration file, created by
# sphinx-quickstart on Thu Mar 16 12:24:11 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath("../"))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = "1.0"

extensions = ["sphinx.ext.autodoc"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = [".rst", ".md"]
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "contextional"
copyright = "2017, Chris NeJame"
author = "Chris NeJame"

release = "1.1.0"

language = None

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

html_theme = "sphinx_rtd_theme"

html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
html_static_path = ["_static"]

htmlhelp_basename = "contextionaldoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
}

latex_documents = [
    (master_doc, "contextional.tex", "contextional Documentation",
     "Chris NeJame", "manual"),
]

# -- Options for manual page output ---------------------------------------

man_pages = [
    (master_doc, "contextional", "contextional Documentation",
     [author], 1),
]

# -- Options for Texinfo output -------------------------------------------

texinfo_documents = [
    (master_doc, "contextional", "contextional Documentation",
     author, "contextional", "One line description of project.",
     "Miscellaneous"),
]
